/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRedirectRouteImport } from './routes/auth-redirect'
import { Route as OsIndexRouteImport } from './routes/os.index'
import { Route as OsIdRouteImport } from './routes/os.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/auth-redirect',
  path: '/auth-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIndexRoute = OsIndexRouteImport.update({
  id: '/os/',
  path: '/os/',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIdRoute = OsIdRouteImport.update({
  id: '/os/$id',
  path: '/os/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-redirect': typeof AuthRedirectRoute
  '/os/$id': typeof OsIdRoute
  '/os/': typeof OsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-redirect': typeof AuthRedirectRoute
  '/os/$id': typeof OsIdRoute
  '/os': typeof OsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-redirect': typeof AuthRedirectRoute
  '/os/$id': typeof OsIdRoute
  '/os/': typeof OsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth-redirect' | '/os/$id' | '/os/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth-redirect' | '/os/$id' | '/os'
  id: '__root__' | '/' | '/auth-redirect' | '/os/$id' | '/os/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
  OsIdRoute: typeof OsIdRoute
  OsIndexRoute: typeof OsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-redirect': {
      id: '/auth-redirect'
      path: '/auth-redirect'
      fullPath: '/auth-redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/': {
      id: '/os/'
      path: '/os'
      fullPath: '/os/'
      preLoaderRoute: typeof OsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/$id': {
      id: '/os/$id'
      path: '/os/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof OsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRedirectRoute: AuthRedirectRoute,
  OsIdRoute: OsIdRoute,
  OsIndexRoute: OsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
